import { builder } from './builder'

// Import enums so they register with the builder (must come before types that reference them)
import './enums/workspace.enum'
import './enums/category.enum'
import './enums/specialty.enum'
import './enums/schedule.enum'
import './enums/shift.enum'
import './enums/assignment.enum'
import './enums/transfer-request.enum'
import './enums/candidate.enum'
import './enums/request.enum'
import './enums/time-entry.enum'
import './enums/shift-timeline.enum'
import './enums/notification.enum'
import './enums/plan-tier.enum'
import './enums/shipment.enum'
import './enums/proposal.enum'
import './enums/carrier-document.enum'

// Import types so they register with the builder
import './types/user.type'
import './types/tenant.type'
import './types/tenant-membership.type'
import './types/workspace.type'
import './types/workspace-membership.type'
import './types/category.type'
import './types/specialty.type'
import './types/workspace-specialty-assignment.type'
import './types/schedule.type'
import './types/shift.type'
import './types/shift-pattern.type'
import './types/assignment.type'
import './types/transfer-request.type'
import './types/candidate.type'
import './types/request.type'
import './types/time-entry.type'
import './types/shift-timeline.type'
import './types/notification.type'
import './types/plan-limits.type'
import './types/neighborhood.type'
import './types/shipment.type'
import './types/browse-shipment.type'
import './types/proposal.type'
import './types/queue-entry.type'
import './types/carrier-document.type'

// Import queries
import './queries/me.query'
import './queries/tenants.query'
import './queries/workspaces.query'
import './queries/categories.query'
import './queries/specialties.query'
import './queries/my-workspace-specialties.query'
import './queries/schedules.query'
import './queries/shifts.query'
import './queries/assignments.query'
import './queries/transfer-requests.query'
import './queries/candidates.query'
import './queries/requests.query'
import './queries/time-entries.query'
import './queries/shift-timeline.query'
import './queries/notification.query'
import './queries/plan-limits.query'
import './queries/neighborhoods.query'
import './queries/shipments.query'
import './queries/browse-shipments.query'
import './queries/queue.query'
import './queries/proposal.query'
import './queries/carrier-documents.query'
import './queries/dashboard-metrics.query'

// Import mutations
import './mutations/me.mutation'
import './mutations/tenants.mutation'
import './mutations/workspaces.mutation'
import './mutations/categories.mutation'
import './mutations/specialties.mutation'
import './mutations/workspace-member-specialty.mutation'
import './mutations/schedules.mutation'
import './mutations/shifts.mutation'
import './mutations/assignments.mutation'
import './mutations/assignment-decisions.mutation'
import './mutations/candidates.mutation'
import './mutations/requests.mutation'
import './mutations/time-entries.mutation'
import './mutations/shift-timeline.mutation'
import './mutations/notification.mutation'
import './mutations/shipments.mutation'
import './mutations/queue.mutation'
import './mutations/proposal.mutation'
import './mutations/carrier-documents.mutation'

export const schema = builder.toSchema()
