import { builder } from '../builder'

export const ShiftTimelineEventTypeEnum = builder.enumType(
  'ShiftTimelineEventType',
  {
    values: [
      'CREATED',
      'UPDATED',
      'CANCELLED',
      'COMPOSITION_SET',
      'ASSIGNED',
      'UNASSIGNED',
      'ACCEPTED',
      'REJECTED',
      'TRANSFER_REQUESTED',
      'TRANSFER_APPROVED',
      'TRANSFER_REJECTED',
      'TRANSFER_CANCELLED',
      'CANDIDATE_APPLIED',
      'CANDIDATE_APPROVED',
      'CANDIDATE_REJECTED',
      'CANDIDATE_WITHDRAWN',
      'CLOCK_IN',
      'CLOCK_OUT',
      'CLT_WARNING',
      'PENDING_CLOSURE',
      'COMPLETED',
      'FILLED',
      'UNFILLED',
      'ASSIGNMENT_CANCELLED_BY_OFFER',
      'ASSIGNMENT_CANCELLED_BY_TIME_OFF',
      'REQUEST_SWAP_SUBMITTED',
      'REQUEST_SWAP_APPROVED',
      'REQUEST_SWAP_REJECTED',
      'REQUEST_SWAP_CANCELLED',
      'REQUEST_SWAP_PEER_ACCEPTED',
      'REQUEST_SWAP_PEER_REJECTED',
      'REQUEST_OFFER_SUBMITTED',
      'REQUEST_OFFER_APPROVED',
      'REQUEST_OFFER_REJECTED',
      'REQUEST_OFFER_CANCELLED',
      'NOTE_ADDED',
    ] as const,
  },
)
